FROM drozzoff/xsuite:latest-gsihpc
ARG TF_ROCM_VERSION=2.16.2
ARG ROCM_SERIES=6.3.4

RUN apt-get update && apt-get install -y --no-install-recommends rocm-hip-runtime
RUN apt-get install -y --no-install-recommends rocm-hip-libraries
RUN apt-get install -y --no-install-recommends rocm-ml-libraries
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends rocblas-dev-rpath${ROCM_SERIES} \
    || { \
        echo "=== /var/log/apt/term.log ==="; \
        cat /var/log/apt/term.log || true; \
        echo "=== /var/log/dpkg.log ==="; \
        cat /var/log/dpkg.log || true; \
        exit 1; \
    }
RUN apt-get install -y --no-install-recommends miopen-hip-dev-rpath${ROCM_SERIES}

RUN python3 -m pip install --no-cache-dir \
	tensorflow-rocm==${TF_ROCM_VERSION} \
	-f https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3/

RUN ln -sf /opt/rocm/lib/librocblas.so.4 /opt/rocm/lib/librocblas.so && \
	ln -sf /opt/rocm/lib/libMIOpen.so.1 /opt/rocm/lib/libMIOpen.so && \
	ln -sf /opt/rocm/lib/libhipfft.so.0 /opt/rocm/lib/libhipfft.so

RUN python3 -c "import tensorflow as tf; print(tf.__version__)"

CMD ["bash"]